### ISSUE TITLE
Loan Migration: incorrect barcode

### ISSUE THREAD

**Issue by wwelling** [TAMULib/mod-data-migration#122]
1.	This is the biggest, most frequently occurring. The program is trying to check out an item to the user using the wrong user barcode, because there is a discrepancy between the amdb and msdb barcodes. Either amdb doesn't have one and the uin gets supplied, while msdb has a "normal" barcode or the amdb and msdb barcodes simply don't match. I think we need to do a couple of things here:
     a.	If the institution ids match between amdb and msdb, indicating the same user, the amdb barcode is preferred, if it exists. But if msdb has a barcode and amdb doesn't then the msdb barcode should be used. The institution_id or xxdb_patron_id should be supplied as a barcode ONLY if both the amdb.patron_barcode and msdb.patron_barcode are lacking a barcode value for the patron.
     b.	Second, when it comes to selecting a user barcode for the loan (or request), let's not try to replicate the logic of barcode selection from the user migration stage. Use the user reference link table to look up the barcode from the user record in the folio database. You put a step in at one point to make sure the same user from amdb and msdb would get the same uuid in the reference link file – all you have to do is use that to do a db lookup. With no more than about 7K unique patron_ids I think it's worth it to eliminate the bulk of the loan failures we saw this time around.
     c.	All of the foregoing has implications for the use of the "uuid from hash" proposal, I think. I'm not sure that's an appropriate technique for users unless logic is put in to guarantee that the same user from both databases, based on matching patron.institution_id, ends up with the same uuid.
2.	Migrate all users as active, giving them a future expiration date. Again, we're running into problems because a user isn't active in amdb but is in msdb. I thought we'd done this at one point, but maybe not or maybe it's just the "cross-database" problem again.
3.	There are 2 item records with the same barcode, so the system can't handle it. Turns out there are almost 1K item records with the same barcode in both databases. This typically happens because evans or blcc will send an item to msl to be put on msl reserve and msl creates another item record for it with the barcode that's in the book. No conflict in Voyager because different databases and no conflict in FOLIO 'cause we don't go through the api when creating the items. I can ask the libraries to do maintenance and get rid of the obsolete duplicate item records, but if such a dup is currently checked out, we'll just have to fix the situation by hand.
4.	Miscellaneous
     a.	Error message appeared to be bogus; items were actually checked out to user.
     b.	Item was noncirc loan type, so it wasn't supposed to check out. Will have to be fixed by hand.
     c.	Can't figure out why it failed; item checked out again through the UI.

**Comment by wwelling** [comment]
meanwhile, on the locations above for which you are missing service points, they all have service point location codes assigned in locations.txt (last column of the following)
msdb	43	ac7da1d1-23f7-4892-9ea6-89d935ea9037	am	cs	msl	ResDesk RESERVES DESK   MSL Reserves Circulation Desk; Not a shelving location  CircDesk
amdb	136	6daff586-2421-47c0-9026-e0511347a752	am	cs	blcc	blcc,res		Business Library Reserves	 Business Library Reserves	 blcc,circ
amdb	21	e8a5154e-71a3-4daa-a2d6-f4626c99ffe6	am	cs	psel	psel,res		PSEL Reserves   Policy Sciences & Economics Library Reserve	psel,circ
amdb	19	c2d7b6b5-9847-46ab-9e5c-d85c74dada25	am	cs	psel	psel,ref		psel,ref		Policy Sciences & Economics Library Reference   psel,circ
msdb	68	38530d09-d263-4253-b21f-67700b4cecfb	am	cs	msl	Mobile  MSL Mobile	MSL Reserve	CircDesk

**Comment by wwelling** [comment]
```
if AMDB barcode is not null
  assign AMDB barcode to FOLIO user barcode
else if AMDB barcode is null AND MSDB barcode is not null
  assign MSDB barcode to FOLIO user barcode
else if external system id is not null in either AMDB or MSDB
  assign external system id to FOLIO user barcode
else assign {schema}_patron.patron_id to FOLIO user barcode
```

**Comment by hismith** [comment]
uin 910001868 = patron group 'prob'. Have referred issue to RBarnes
A4850452609 is an inactive barcode (barcode status = 2) for the item in question. Selection criteria should specify barcode_status = 1;
A14813727252 is noncirculating
3238902095053 is noncirculating
3238902095086 is noncirculating
3238902561512 is noncirculating
