### ISSUE TITLE
Item Migration: update item types and maps

### ISSUE THREAD

**Issue by wwelling** [TAMULib/mod-data-migration#203]
I have posted a file named item_suppl.tar.gz to the Migration dropoff drive. It contains the current json for loan_types for item migration and an updated voyager item type to folio loan type map. I'm getting rid of a few more loan types, so I think it would easiest if you deleted all the reference data json for loan types that you have and use what's in the file. Also, as I said, you'll need to update the maps in the code. I've tried my best to check this against what's actually in Voyager so that we still have all the data we need for migration.

**Comment by hismith** [comment]
Can be marked resolved.

**Comment by hismith** [comment]
Can be marked resolved.
