### ISSUE TITLE
Loan migration: trying to check out to incorrect barcode

### ISSUE THREAD

**Issue by hismith** [TAMULib/mod-data-migration#309]
The error message AMDB failed to checkout item with barcode A4850452609 to user with barcode 6016426593603935 (2021-12-01 18:40:43.554 ERROR 6) is bogus. 

Barcode A4850452609 is an inactive barcode for that item. The item in question, with active barcode A14850452765, is correctly charged out to the patron in question in FOLIO.
 
same is true of MSDB failed to checkout item with barcode 323890001311V to user with barcode 124005548 at service point MSL AskUs, that's an inactive barcode.

**Comment by wwelling** [comment]
```
AND ib.barcode_status = '1'
```
