### ISSUE TITLE
Purchase Orders Migration

### ISSUE THREAD

**Issue by wwelling** [TAMULib/mod-data-migration#46]

**Comment by hismith** [comment]
Assignment of Funddistribution looks correct, which was the only outstanding issue for this run. Will need 1 or 2 new cards for next run of purchase orders: 1) decision on how to assign fund/expense class for galveston funds; 2) addition of productIds.

**Comment by wwelling** [comment]
Closing with the creation of 2 additional purchase order issues.

**Comment by wwelling** [comment]
https://github.com/TAMULib/mod-data-migration/issues/207

**Comment by wwelling** [comment]
https://github.com/TAMULib/mod-data-migration/issues/208
